name: rahroo
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  dio: "4.0.4"
  provider: ^6.0.5
  google_fonts: ^5.1.0
  cupertino_icons: ^1.0.2
  file_picker: ^5.3.3
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  firebase_analytics: ^10.4.4
  icloud_storage: ^2.2.0
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
